//AV1:
//P3: 60 melee, 30 antihorse, 32 archers, 48 mounted
//P4: 27 melee, 27 antihorse, 24 archers, 18 mounted
//P5: 54 mounted
//P6: 60 mounted
//P7: 54 mounted
//P8: 48 melee, 24 antihorse, 32 archers, 36 mounted
//P9: 24 mounted
//P10: 24 melee, 12 antihorse, 24 archers, 18 mounted
//P11: 60 melee, 36 antihorse, 24 archers
//P12: 24 mounted
//P16: 72 mounted

//AV2:
//P3: 48 mounted
//P4: 54 mounted
//P5: 54 mounted
//P6: 60 mounted
//P7: 54 mounted
//P8: 108 mounted
//P9: 24 mounted
//P10: 27 mounted
//P11: 99 mounted
//P12: 24 mounted
//P16: 72 mounted

procedure PreparingEnemyAttacks(i, j: Integer); //i = player no.-1, j = variation; variation 1 = melee etc, variation 2 = mounted
begin	
	if (i = 2) then
		begin
			A.AIAttackRemoveAll(2);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[2],76,82); 
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[2],53,94);
					end;
			end;
			if (j = 1) then				
				begin
					A.AIDefencePositionAdd (PlayerNumber[2], 36, 62, 2, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[2], 32, 60, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 32, 65, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 28, 62, 2, 3, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[2], 21, 48, 4, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 27, 48, 4, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 21, 44, 4, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 27, 44, 4, 0, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[2], 27, 52, 4, 1, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 24, 36, 4, 1, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[2], 21, 41, 4, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 26, 41, 4, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 21, 39, 4, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 26, 39, 4, 2, 20, 0);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[2], 36, 62, 2, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[2], 32, 60, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 32, 65, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[2], 28, 62, 2, 3, 20, 0);
				end;	
		end else
	if (i = 3) then
		begin
			A.AIAttackRemoveAll(3);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[3],76,82);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[3],53,94);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[3], 71, 31, 4, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[3], 71, 27, 4, 3, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[3], 51, 66, 4, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 51, 62, 4, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 55, 62, 4, 0, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[3], 60, 64, 4, 1, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 65, 62, 4, 1, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 60, 60, 4, 1, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[3], 50, 59, 4, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 54, 59, 4, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[3], 65, 59, 4, 2, 20, 0);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[3], 95, 38, 2, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[3], 95, 41, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[3], 99, 38, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[3], 99, 41, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[3], 103, 38, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[3], 103, 41, 2, 3, 20, 0); 
				end;		
		end else
	if (i = 4) then
		begin
			A.AIAttackRemoveAll(4);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[4],76,82);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[4],53,94);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 30, 2, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 34, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 45, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 49, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 99, 32, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 99, 47, 2, 3, 20, 0); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 30, 2, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 34, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 45, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 95, 49, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 99, 32, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[4], 99, 47, 2, 3, 20, 0); 
				end;	
		end else
	if (i = 5) then
		begin
			A.AIAttackRemoveAll(5);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[5],138,107);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[5],120,97);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[5], 162, 23, 5, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[5], 166, 26, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 159, 26, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 163, 29, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 42, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 42, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 39, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 39, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 36, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 36, 4, 3, 20, 0); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[5], 162, 23, 5, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[5], 166, 26, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 159, 26, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 163, 29, 5, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 42, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 42, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 39, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 39, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 185, 36, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[5], 189, 36, 4, 3, 20, 0); 
				end;	
		end else
	if (i = 6) then
		begin
			A.AIAttackRemoveAll(6);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[6],138,107);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[6],120,97);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[6], 174, 45, 4, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[6], 178, 45, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 182, 45, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 174, 41, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 178, 41, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 182, 41, 4, 3, 20, 0);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[6], 174, 45, 4, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[6], 178, 45, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 182, 45, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 174, 41, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 178, 41, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[6], 182, 41, 4, 3, 20, 0);
				end;	
		end else
	if (i = 7) then
		begin
			A.AIAttackRemoveAll(7);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[7],138,107);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[7],120,97);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[7], 131, 82, 4, 0, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[7], 136, 82, 4, 0, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 131, 78, 4, 0, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 136, 78, 4, 0, 20, 0); 
					
					A.AIDefencePositionAdd (PlayerNumber[7], 131, 70, 4, 1, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 136, 70, 4, 1, 20, 0); 
					
					A.AIDefencePositionAdd (PlayerNumber[7], 131, 74, 4, 2, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 136, 74, 4, 2, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 131, 72, 4, 2, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 136, 72, 4, 2, 20, 0); 
					
					A.AIDefencePositionAdd (PlayerNumber[7], 127, 80, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 127, 76, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 127, 72, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 141, 78, 4, 3, 20, 0);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[7], 130, 82, 4, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[7], 134, 82, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 126, 78, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 130, 78, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 134, 78, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[7], 138, 78, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 126, 74, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 130, 74, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 134, 74, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 138, 74, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 130, 70, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[7], 134, 70, 4, 3, 20, 0);
				end;	
		end else
	if (i = 8) then
		begin
			A.AIAttackRemoveAll(8);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[8],66,109);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[8],64,131);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[8], 10, 105, 4, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[8], 15, 97, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[8], 21, 95, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[8], 32, 104, 4, 3, 20, 0); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[8], 10, 105, 4, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[8], 15, 97, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[8], 21, 95, 4, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[8], 32, 104, 4, 3, 20, 0); 
				end;
		end else
	if (i = 9) then
		begin
			A.AIAttackRemoveAll(9);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[9],66,109);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[9],64,131);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[9], 25, 141, 4, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[9], 15, 139, 4, 3, 20, 0); 
					
					A.AIDefencePositionAdd (PlayerNumber[9], 53, 132, 2, 0, 20, 0);	
					A.AIDefencePositionAdd (PlayerNumber[9], 53, 142, 2, 0, 20, 0);	

					A.AIDefencePositionAdd (PlayerNumber[9], 53, 137, 2, 1, 20, 0);	
					A.AIDefencePositionAdd (PlayerNumber[9], 48, 137, 2, 1, 20, 0);	

					A.AIDefencePositionAdd (PlayerNumber[9], 50, 132, 2, 2, 20, 0);	
					A.AIDefencePositionAdd (PlayerNumber[9], 50, 137, 2, 2, 20, 0);	
					A.AIDefencePositionAdd (PlayerNumber[9], 50, 142, 2, 2, 20, 0);						
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[9], 52, 131, 2, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[9], 52, 136, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[9], 52, 141, 2, 3, 20, 0);	
				end;	
		end else
	if (i = 10) then
		begin
			A.AIAttackRemoveAll(10);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[10],66,109);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[10],64,131);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[10], 25, 166, 2, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 155, 2, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 160, 2, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 175, 2, 0, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 180, 2, 0, 20, 0);

					A.AIDefencePositionAdd (PlayerNumber[10], 30, 183, 2, 1, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 30, 187, 2, 1, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 20, 166, 2, 1, 20, 0);

					A.AIDefencePositionAdd (PlayerNumber[10], 22, 166, 2, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 27, 183, 2, 2, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 27, 187, 2, 2, 20, 0);			
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 153, 2, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 157, 2, 3, 20, 0); 
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 161, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 174, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 178, 2, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 22, 182, 2, 3, 20, 0);
					
					A.AIDefencePositionAdd (PlayerNumber[10], 27, 184, 1, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 31, 187, 1, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 35, 189, 0, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 41, 189, 0, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[10], 45, 189, 0, 3, 20, 0);
				end;	
		end else
	if (i = 11) then
		begin
			A.AIAttackRemoveAll(11);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[11],66,109);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[11],64,131);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[11], 11, 18, 3, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[11], 22, 8, 3, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[11], 14, 15, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[11], 18, 12, 2, 3, 20, 0);					
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[11], 11, 18, 3, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[11], 22, 8, 3, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[11], 14, 15, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[11], 18, 12, 2, 3, 20, 0);
				end;	
		end else
	if (i = 15) then
		begin
			A.AIAttackRemoveAll(15);
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIStartPosition(PlayerNumber[15],76,82);
					end;
				1: begin
						A.AIStartPosition(PlayerNumber[15],53,94);
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[15], 32, 9, 4, 3, 20, 0); //add attack variation 1
					A.AIDefencePositionAdd (PlayerNumber[15], 38, 7, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 43, 7, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 33, 5, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 38, 3, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 43, 3, 4, 3, 20, 0);					
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionAdd (PlayerNumber[15], 32, 9, 4, 3, 20, 0); //add attack variation 2
					A.AIDefencePositionAdd (PlayerNumber[15], 38, 7, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 43, 7, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 33, 5, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 38, 3, 4, 3, 20, 0);
					A.AIDefencePositionAdd (PlayerNumber[15], 43, 3, 4, 3, 20, 0);
				end;	
		end;
end;