procedure SendingEnemyAttacks(i, j: Integer); //i = player no.-1, j = variation; variation 1 = melee etc, variation 2 = mounted
begin	
	if (i = 2) then
		begin	
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[2], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[2], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then				
				begin
					A.AIDefencePositionRemove (PlayerNumber[2], 36, 62); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[2], 32, 60);
					A.AIDefencePositionRemove (PlayerNumber[2], 32, 65);
					A.AIDefencePositionRemove (PlayerNumber[2], 28, 62);
					
					A.AIDefencePositionRemove (PlayerNumber[2], 21, 48);
					A.AIDefencePositionRemove (PlayerNumber[2], 27, 48);
					A.AIDefencePositionRemove (PlayerNumber[2], 21, 44);
					A.AIDefencePositionRemove (PlayerNumber[2], 27, 44);
					
					A.AIDefencePositionRemove (PlayerNumber[2], 27, 52);
					A.AIDefencePositionRemove (PlayerNumber[2], 24, 36);
					
					A.AIDefencePositionRemove (PlayerNumber[2], 21, 41);
					A.AIDefencePositionRemove (PlayerNumber[2], 26, 41);
					A.AIDefencePositionRemove (PlayerNumber[2], 21, 39);
					A.AIDefencePositionRemove (PlayerNumber[2], 26, 39);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[2], 36, 62); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[2], 32, 60);
					A.AIDefencePositionRemove (PlayerNumber[2], 32, 65);
					A.AIDefencePositionRemove (PlayerNumber[2], 28, 62);
				end;	
		end else
	if (i = 3) then
		begin	
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[3], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[3], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[3], 71, 31); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[3], 71, 27);
					
					A.AIDefencePositionRemove (PlayerNumber[3], 51, 66);
					A.AIDefencePositionRemove (PlayerNumber[3], 51, 62);
					A.AIDefencePositionRemove (PlayerNumber[3], 55, 62);
					
					A.AIDefencePositionRemove (PlayerNumber[3], 60, 64);
					A.AIDefencePositionRemove (PlayerNumber[3], 65, 62);
					A.AIDefencePositionRemove (PlayerNumber[3], 60, 60);
					
					A.AIDefencePositionRemove (PlayerNumber[3], 50, 59);
					A.AIDefencePositionRemove (PlayerNumber[3], 54, 59);
					A.AIDefencePositionRemove (PlayerNumber[3], 65, 59);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[3], 95, 38); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[3], 95, 41); 
					A.AIDefencePositionRemove (PlayerNumber[3], 99, 38); 
					A.AIDefencePositionRemove (PlayerNumber[3], 99, 41); 
					A.AIDefencePositionRemove (PlayerNumber[3], 103, 38); 
					A.AIDefencePositionRemove (PlayerNumber[3], 103, 41); 
				end;		
		end else
	if (i = 4) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[4], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[4], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 30); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 34); 
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 45); 
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 49); 
					A.AIDefencePositionRemove (PlayerNumber[4], 99, 32); 
					A.AIDefencePositionRemove (PlayerNumber[4], 99, 47); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 30); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 34); 
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 45); 
					A.AIDefencePositionRemove (PlayerNumber[4], 95, 49); 
					A.AIDefencePositionRemove (PlayerNumber[4], 99, 32); 
					A.AIDefencePositionRemove (PlayerNumber[4], 99, 47); 
				end;	
		end else
	if (i = 5) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[5], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[5], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[5], 162, 23); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[5], 166, 26); 
					A.AIDefencePositionRemove (PlayerNumber[5], 159, 26); 
					A.AIDefencePositionRemove (PlayerNumber[5], 163, 29); 
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 42); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 42);
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 39); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 39); 
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 36); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 36); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[5], 162, 23); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[5], 166, 26); 
					A.AIDefencePositionRemove (PlayerNumber[5], 159, 26); 
					A.AIDefencePositionRemove (PlayerNumber[5], 163, 29); 
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 42); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 42);
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 39); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 39); 
					A.AIDefencePositionRemove (PlayerNumber[5], 185, 36); 
					A.AIDefencePositionRemove (PlayerNumber[5], 189, 36); 
				end;	
		end else
	if (i = 6) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[6], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[6], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[6], 174, 45); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[6], 178, 45); 
					A.AIDefencePositionRemove (PlayerNumber[6], 182, 45); 
					A.AIDefencePositionRemove (PlayerNumber[6], 174, 41); 
					A.AIDefencePositionRemove (PlayerNumber[6], 178, 41); 
					A.AIDefencePositionRemove (PlayerNumber[6], 182, 41);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[6], 174, 45); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[6], 178, 45); 
					A.AIDefencePositionRemove (PlayerNumber[6], 182, 45); 
					A.AIDefencePositionRemove (PlayerNumber[6], 174, 41); 
					A.AIDefencePositionRemove (PlayerNumber[6], 178, 41); 
					A.AIDefencePositionRemove (PlayerNumber[6], 182, 41);
				end;	
		end else
	if (i = 7) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[7], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[7], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[7], 131, 82); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[7], 136, 82); 
					A.AIDefencePositionRemove (PlayerNumber[7], 131, 78); 
					A.AIDefencePositionRemove (PlayerNumber[7], 136, 78); 
					
					A.AIDefencePositionRemove (PlayerNumber[7], 131, 70); 
					A.AIDefencePositionRemove (PlayerNumber[7], 136, 70); 
					
					A.AIDefencePositionRemove (PlayerNumber[7], 131, 74); 
					A.AIDefencePositionRemove (PlayerNumber[7], 136, 74); 
					A.AIDefencePositionRemove (PlayerNumber[7], 131, 72); 
					A.AIDefencePositionRemove (PlayerNumber[7], 136, 72); 
					
					A.AIDefencePositionRemove (PlayerNumber[7], 127, 80); 
					A.AIDefencePositionRemove (PlayerNumber[7], 127, 76); 
					A.AIDefencePositionRemove (PlayerNumber[7], 127, 72); 
					A.AIDefencePositionRemove (PlayerNumber[7], 141, 78);
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[7], 130, 82); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[7], 134, 82); 
					A.AIDefencePositionRemove (PlayerNumber[7], 126, 78); 
					A.AIDefencePositionRemove (PlayerNumber[7], 130, 78); 
					A.AIDefencePositionRemove (PlayerNumber[7], 134, 78); 
					A.AIDefencePositionRemove (PlayerNumber[7], 138, 78);
					A.AIDefencePositionRemove (PlayerNumber[7], 126, 74);
					A.AIDefencePositionRemove (PlayerNumber[7], 130, 74);
					A.AIDefencePositionRemove (PlayerNumber[7], 134, 74);
					A.AIDefencePositionRemove (PlayerNumber[7], 138, 74);
					A.AIDefencePositionRemove (PlayerNumber[7], 130, 70);
					A.AIDefencePositionRemove (PlayerNumber[7], 134, 70);
				end;	
		end else
	if (i = 8) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[8], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[8], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[8], 10, 105); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[8], 15, 97); 
					A.AIDefencePositionRemove (PlayerNumber[8], 21, 95); 
					A.AIDefencePositionRemove (PlayerNumber[8], 32, 104); 
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[8], 10, 105); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[8], 15, 97); 
					A.AIDefencePositionRemove (PlayerNumber[8], 21, 95); 
					A.AIDefencePositionRemove (PlayerNumber[8], 32, 104); 
				end;
		end else
	if (i = 9) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[9], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[9], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[9], 25, 141); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[9], 15, 139); 
					
					A.AIDefencePositionRemove (PlayerNumber[9], 53, 132);	
					A.AIDefencePositionRemove (PlayerNumber[9], 53, 142);	

					A.AIDefencePositionRemove (PlayerNumber[9], 53, 137);	
					A.AIDefencePositionRemove (PlayerNumber[9], 48, 137);	

					A.AIDefencePositionRemove (PlayerNumber[9], 50, 132);	
					A.AIDefencePositionRemove (PlayerNumber[9], 50, 137);	
					A.AIDefencePositionRemove (PlayerNumber[9], 50, 142);						
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[9], 52, 131); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[9], 52, 136); 
					A.AIDefencePositionRemove (PlayerNumber[9], 52, 141);	
				end;	
		end else
	if (i = 10) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[10], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[10], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[10], 25, 166);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 155);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 160);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 175);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 180);

					A.AIDefencePositionRemove (PlayerNumber[10], 30, 183);
					A.AIDefencePositionRemove (PlayerNumber[10], 30, 187);
					A.AIDefencePositionRemove (PlayerNumber[10], 20, 166);

					A.AIDefencePositionRemove (PlayerNumber[10], 22, 166);
					A.AIDefencePositionRemove (PlayerNumber[10], 27, 183);
					A.AIDefencePositionRemove (PlayerNumber[10], 27, 187);			
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 153); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 157); 
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 161);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 174);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 178);
					A.AIDefencePositionRemove (PlayerNumber[10], 22, 182);
					
					A.AIDefencePositionRemove (PlayerNumber[10], 27, 184);
					A.AIDefencePositionRemove (PlayerNumber[10], 31, 187);
					A.AIDefencePositionRemove (PlayerNumber[10], 35, 189);
					A.AIDefencePositionRemove (PlayerNumber[10], 41, 189);
					A.AIDefencePositionRemove (PlayerNumber[10], 45, 189);
				end;	
		end else
	if (i = 11) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[11], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[11], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[11], 11, 18); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[11], 22, 8);
					A.AIDefencePositionRemove (PlayerNumber[11], 14, 15);
					A.AIDefencePositionRemove (PlayerNumber[11], 18, 12);					
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[11], 11, 18); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[11], 22, 8);
					A.AIDefencePositionRemove (PlayerNumber[11], 14, 15);
					A.AIDefencePositionRemove (PlayerNumber[11], 18, 12);
				end;	
		end else
	if (i = 15) then
		begin
			case U.RandomRangeI(0, 1) of
				0: begin
						A.AIAttackAdd (PlayerNumber[15], true, 0, 1, 0, 0, 0, 0, true, attClosestBuildingFromStartPos, U.KMPoint(0, 0));
					end;
				1: begin
						A.AIAttackAdd (PlayerNumber[15], true, 0, 1, 0, 0, 0, 0, true, attClosestUnit, U.KMPoint(0, 0));
					end;
			end;
			if (j = 1) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[15], 32, 9); //add attack variation 1
					A.AIDefencePositionRemove (PlayerNumber[15], 38, 7);
					A.AIDefencePositionRemove (PlayerNumber[15], 43, 7);
					A.AIDefencePositionRemove (PlayerNumber[15], 33, 5);
					A.AIDefencePositionRemove (PlayerNumber[15], 38, 3);
					A.AIDefencePositionRemove (PlayerNumber[15], 43, 3);					
				end else
			if (j = 2) then
				begin
					A.AIDefencePositionRemove (PlayerNumber[15], 32, 9); //add attack variation 2
					A.AIDefencePositionRemove (PlayerNumber[15], 38, 7);
					A.AIDefencePositionRemove (PlayerNumber[15], 43, 7);
					A.AIDefencePositionRemove (PlayerNumber[15], 33, 5);
					A.AIDefencePositionRemove (PlayerNumber[15], 38, 3);
					A.AIDefencePositionRemove (PlayerNumber[15], 43, 3);
				end;	
		end;
end;